apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-pod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: update-pod