kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-app-db-vault
data:
  application.yml: |
    spring:
      application:
        name: sample-app-db-vault
      datasource:
        url: jdbc:postgresql://postgresql:5432/postgres

      config:
        import: vault://
      cloud:
        vault:
          config.lifecycle:
            enabled: true
            kv.backend:   kv
            min-renewal: 10s
            expiry-threshold: 30s
          kv.enabled: false
          uri: http://vault.vault:8200
          authentication: KUBERNETES
          postgresql:
            enabled: true
            role: postgresql-default-role
            backend: database
          kubernetes:
            role: database-engine-creds-role