apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-db-vault
spec:
  selector:
    matchLabels:
      app: sample-app-db-vault
  template:
    metadata:
      labels:
        app: sample-app-db-vault
    spec:
      containers:
        - name: sample-app-db-vault
          image: riarana1/sample-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/config/application.yml
          volumeMounts:
            - mountPath: /opt/config
              name: config
      volumes:
        - name: config
          configMap:
            name: sample-app-db-vault
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-db-vault
spec:
  type: ClusterIP
  selector:
    app: sample-app-db-vault
  ports:
    - port: 8080